name: Build and tests eshop workflow

on:
  workflow_dispatch:
  push: 

jobs:
  Install:
    runs-on: ubuntu-latest
    
    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
        
      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v4.0.2
        with: 
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-

      - name: Install packages with npm
        run:
          npm ci  

  Build:
    needs: Install
    runs-on: ubuntu-latest
      
    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:          
          token: ${{ secrets.WORKFLOW_TOKEN }}
          
      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v4.0.2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: |
          npm rebuild node-sass --force
          npm run build -- --colors

      - name: Cache node modules and build
        if: ${{ github.ref == 'refs/heads/main'}}
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.npm
            ./node_modules
            ./build
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-build-${{ github.run_id }}

  Test :
    needs: Install
    runs-on: ubuntu-latest
      
    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:          
          token: ${{ secrets.WORKFLOW_TOKEN }}
          
      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v4.0.2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Run unit
        run: |
          npm rebuild node-sass --force
          npm run test -- --colors

  Deploy: 
    needs: [Build, Test]
    # if: ${{ github.ref == 'refs/heads/main'}}
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:          
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5.1.0

      - name: Install essentials
        run: pip3 install ansible boto boto3

      - name: Create pem file
        run: |
          echo "${{ secrets.EC2_KEY }}" > test.pem
          chmod 400 test.pem

      - name: Create Vault File
        run: |
          mkdir -p group_vars/all/
          echo 'access_key: ${{ secrets.AWS_ACCESS_KEY }}' > group_vars/all/aws.yml
          echo 'secret_key: ${{ secrets.AWS_SECRET_KEY }}' >> group_vars/all/aws.yml
          echo 'session_token: ${{ secrets.AWS_SESSION_TOKEN }}' >> group_vars/all/aws.yml
          ansible-vault encrypt group_vars/all/aws.yml --vault-password-file=<(echo "${{ secrets.VAULT_PASSWORD }}")

      - name: Run deploy script in AWS EC 2
        run: ansible-playbook ansible/ec2_deploy.yml --vault-password-file=<(echo "${{ secrets.VAULT_PASSWORD }}") --user ec2-user --key-file test.pem