name: Build and tests eshop workflow

on:
  workflow_dispatch:
  push: 

jobs:
  Install:
    runs-on: ubuntu-latest
    
    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
        
      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v4.0.2
        with: 
          path: node_modules
          key: node_modules-${{ hashFiles('***/pachage-lock.json') }}
          restore-keys: node_modules-

      - name: Install packages with npm
        run:
          npm ci  

  Build:
    needs: Install
    runs-on: ubuntu-latest
      
    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:          
          token: ${{ secrets.WORKFLOW_TOKEN }}
          
      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v4.0.2
        with: 
          path: node_modules
          key: node_modules-${{ hashFiles('***/pachage-lock.json') }}

      - name: Build
        run: 
          npm rebuild node-sass --force
          npm run build -- --colours

  Test :
    needs: Install
    runs-on: ubuntu-latest
      
    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:          
          token: ${{ secrets.WORKFLOW_TOKEN }}
          
      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v4.0.2
        with: 
          path: node_modules
          key: node_modules-${{ hashFiles('***/pachage-lock.json') }}

      - name: Run unit
        run: 
          npm rebuild node-sass --force
          npm run test -- --colours
  
            
        
      